spring.application.name=confectionco

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-oayu8epftihuelj1.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://confectionco-api

aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.bucket-assets=${AWS_BUCKET_ASSETS}
aws.bucket-inspo=${AWS_BUCKET_INSPO}
aws.bucket-url=${AWS_BUCKET_URL}